#!/bin/bash

DIR16=Debug_Unicode
DIR8=Debug
EXPORT_OPTS=-xr
LONG_ROOT_KEYS="HKEY_CURRENT_CONFIG HKEY_CURRENT_USER HKEY_CLASSES_ROOT HKEY_LOCAL_MACHINE HKEY_USERS"
ROOT_KEYS="HKCC HKCU HKCR HKLM HKU"
TIMEIT=timeit.exe
WINMERGE16=C:/Program\ Files/WinMerge/WinMergeU.exe
WINMERGE8=C:/Program\ Files/WinMerge/WinMerge.exe

if [ "$1" = "16" ]
then
	DIR=$DIR16
	WINMERGE=$WINMERGE16
else
	DIR=$DIR8
	WINMERGE=$WINMERGE8
fi
